Repository apache/skywalking-booster-ui, pull requests merged in 2022-04, with the labels that each got.

#50 fix: update style and set labels
  src/layout/components/NavBar.vue
  src/views/dashboard/configuration/Widget.vue
  src/views/dashboard/configuration/widget/metric/Index.vue
  src/views/dashboard/configuration/widget/metric/Standard.vue
  src/views/dashboard/graphs/EndpointList.vue
  src/views/dashboard/graphs/InstanceList.vue
  src/views/dashboard/graphs/ServiceList.vue
  src/views/dashboard/panel/Tool.vue
Labels: bug

#51 refactor: update legend for topology
  src/views/dashboard/graphs/Bar.vue
  src/views/dashboard/related/topology/components/Graph.vue
  src/views/dashboard/related/topology/components/Sankey.vue
  src/views/dashboard/related/topology/utils/legend.ts
Labels: bug, enhancement

#53 feat: add a calculation and update selectors param
  src/hooks/data.ts
  src/hooks/useProcessor.ts
  src/layout/components/NavBar.vue
  src/views/dashboard/controls/Text.vue
  src/views/dashboard/controls/Widget.vue
  src/views/dashboard/data.ts
  src/views/dashboard/graphs/EndpointList.vue
  src/views/dashboard/graphs/InstanceList.vue
  src/views/dashboard/graphs/ServiceList.vue
  src/views/dashboard/panel/Tool.vue
Labels: bug, enhancement

#54 fix: update selector params and list graphs
  src/components/Graph.vue
  src/views/dashboard/configuration/Widget.vue
  src/views/dashboard/graphs/EndpointList.vue
  src/views/dashboard/graphs/InstanceList.vue
  src/views/dashboard/panel/Tool.vue
Labels: bug

#55 fix: set graph style and topology node services
  src/components/Graph.vue
  src/views/dashboard/related/topology/components/Graph.vue
Labels: bug

#56 fix: update text control styles
  src/views/dashboard/controls/Text.vue
Labels: bug

#57 build: update packages
  package-lock.json
  package.json
  src/styles/reset.scss
Labels: enhancement

#58 fix: add technology icons and update word contents
  src/assets/img/technologies/EXPRESS.png
  src/assets/img/technologies/SPRINGWEBFLUX.png
  src/locales/lang/en.ts
  src/locales/lang/zh.ts
  src/views/Log.vue
  src/views/Settings.vue
  src/views/dashboard/List.vue
  tests/unit/example.spec.ts
Labels: bug

#64 fix: refresh dashboards with current selectors
  src/views/Settings.vue
  src/views/dashboard/panel/Layout.vue
  src/views/dashboard/panel/Tool.vue
Labels: bug

#65 feat: add an avg calculation for metrics of list graphs
  src/assets/icons/timeline.svg
  src/hooks/data.ts
  src/hooks/useListConfig.ts
  src/hooks/useProcessor.ts
  src/store/modules/topology.ts
  src/types/dashboard.ts
  src/views/dashboard/configuration/widget/metric/Index.vue
  src/views/dashboard/controls/Text.vue
  src/views/dashboard/data.ts
  src/views/dashboard/graphs/Card.vue
  src/views/dashboard/graphs/EndpointList.vue
  src/views/dashboard/graphs/InstanceList.vue
  src/views/dashboard/graphs/Line.vue
  src/views/dashboard/graphs/ServiceList.vue
  src/views/dashboard/graphs/components/ColumnGraph.vue
  src/views/dashboard/panel/Layout.vue
Labels: enhancement

#66 feat: add Avg calculations
  src/hooks/data.ts
  src/hooks/useListConfig.ts
  src/hooks/useProcessor.ts
  src/views/dashboard/data.ts
  src/views/dashboard/graphs/Card.vue
Labels: enhancement

#67 fix: keep metrics index
  src/views/dashboard/configuration/widget/metric/Index.vue
Labels: bug

#69 Locale improvements
  src/locales/lang/en.ts
Labels: bug

#71 fix: set UTC when page loads
  src/store/modules/app.ts
  src/views/Settings.vue
Labels: bug

#73 fix: optimize the trace widget
  src/assets/icons/arrow-down.svg
  src/views/dashboard/related/trace/Detail.vue
  src/views/dashboard/related/trace/components/List.vue
  src/views/dashboard/related/trace/utils/d3-trace-list.ts
Labels: bug

#74 fix: avoid invalid query for topology metrics
  src/components/SelectSingle.vue
  src/store/modules/topology.ts
Labels: bug

#75 fix: add the alarm and log tag tips
  src/locales/lang/en.ts
  src/locales/lang/zh.ts
  src/views/components/ConditionTags.vue
Labels: bug
