Repository apache/skywalking-booster-ui, pull requests merged in 2022-09, with the labels that each got.

#152 fix: tab active incorrectly, when click tab space
  src/views/dashboard/controls/Tab.vue
Labels: bug

#154 Keep package.json and package-lock.json in sync
  .github/workflows/nodejs.yml
  package-lock.json
Labels: dependencies

#155 fix: polish the endpoint list graph
  src/locales/lang/en.ts
  src/locales/lang/es.ts
  src/locales/lang/zh.ts
  src/views/dashboard/graphs/EndpointList.vue
  src/views/dashboard/graphs/InstanceList.vue
  src/views/dashboard/graphs/ServiceList.vue
  src/views/dashboard/graphs/style.scss
Labels: enhancement

#156 fix: set up a new time range after clicking the refresh button
  src/layout/components/NavBar.vue
Labels: bug

#157 fix: update styles for an adaptive height
  src/App.vue
  src/layout/components/SideBar.vue
  src/views/dashboard/List.vue
Labels: bug

#158 feat: enhance the process topology graph to support dragging nodes
  src/layout/components/SideBar.vue
  src/store/modules/network-profiling.ts
  src/types/ebpf.d.ts
  src/views/dashboard/controls/Widget.vue
  src/views/dashboard/related/components/utils/zoom.ts
  src/views/dashboard/related/network-profiling/Content.vue
  src/views/dashboard/related/network-profiling/components/Graph/linkProcess.ts
  src/views/dashboard/related/network-profiling/components/Graph/nodeProcess.ts
  src/views/dashboard/related/network-profiling/components/ProcessTopology.vue
Labels: enhancement

#159 Add virtual cache dashboard
  src/constants/data.ts
  src/locales/lang/en.ts
  src/locales/lang/es.ts
  src/locales/lang/zh.ts
  src/router/general.ts
Labels: enhancement

#160 fix: remove All from the endpoints selector
  src/router/general.ts
  src/store/modules/profile.ts
Labels: bug

#161 feat: enhance menu configuration to make it easier to change
  src/constants/data.ts
  src/layout/components/SideBar.vue
  src/router/dashboard.ts
  src/router/data/browser.ts
  src/router/data/database.ts
  src/router/data/functions.ts
  src/router/data/general.ts
  src/router/data/index.ts
  src/router/data/infrastructure.ts
  src/router/data/k8s.ts
  src/router/data/selfObservability.ts
  src/router/data/serviceMesh.ts
  src/router/database.ts
  src/router/index.ts
  src/router/layer.ts
  src/router/setting.ts
  src/views/Layer.vue
Labels: enhancement

#165 fix: query logs with the specific service ID
  src/views/dashboard/related/log/Header.vue
Labels: bug
