Repository apache/skywalking-booster-ui, pull requests merged in 2022-05, with the labels that each got.

#76 fix: view spans details and task logs
  src/store/modules/profile.ts
  src/views/dashboard/related/components/LogTable/LogService.vue
  src/views/dashboard/related/profile/components/TaskList.vue
  src/views/dashboard/related/trace/components/D3Graph/SpanDetail.vue
  src/views/dashboard/related/trace/components/Table/TableItem.vue
Labels: bug

#77 fix: verify query params to avoid invalid queries
  src/store/modules/ebpf.ts
  src/store/modules/profile.ts
  src/views/dashboard/related/profile/components/TaskList.vue
Labels: bug

#78 feat: mobile terminal adaptation
  src/App.vue
  src/layout/components/SideBar.vue
  src/store/modules/app.ts
  src/styles/grid.scss
  src/styles/lib.scss
  src/styles/reset.scss
  src/views/dashboard/controls/Log.vue
  src/views/dashboard/controls/Tab.vue
  src/views/dashboard/controls/Trace.vue
  src/views/dashboard/panel/Tool.vue
  src/views/dashboard/related/components/LogTable/Index.vue
  src/views/dashboard/related/ebpf/components/EBPFSchedules.vue
  src/views/dashboard/related/profile/Content.vue
  src/views/dashboard/related/profile/components/SpanTree.vue
  src/views/dashboard/related/trace/Filter.vue
Labels: enhancement

#79 fix: set dropdown for the Tab widget, init instance relation selectors, update sankey graph
  src/components/Graph.vue
  src/layout/components/SideBar.vue
  src/views/dashboard/controls/Tab.vue
  src/views/dashboard/panel/Tool.vue
  src/views/dashboard/related/topology/components/PodTopology.vue
Labels: bug

#80 fix: set graph options
  src/views/dashboard/configuration/widget/WidgetOptions.vue
  src/views/dashboard/related/topology/components/Graph.vue
  src/views/dashboard/related/topology/components/PodTopology.vue
Labels: bug

#81 feat: remove the layer filed for instance query
  src/graphql/fragments/selector.ts
  src/types/selector.d.ts
Labels: enhancement

#82 feat: remove the layer filed from the Process
  src/graphql/fragments/ebpf.ts
  src/types/ebpf.d.ts
Labels: enhancement

#83 fix: set date to 0 and remove duration filed
  src/components/DateCalendar.vue
  src/store/modules/ebpf.ts
Labels: bug

#84 fix: update schedules query
  src/graphql/fragments/ebpf.ts
  src/locales/lang/en.ts
Labels: bug

#85 feat: Implement tags auto-complete for Trace and Log
  src/graphql/fragments/log.ts
  src/graphql/fragments/trace.ts
  src/graphql/query/log.ts
  src/graphql/query/trace.ts
  src/locales/lang/en.ts
  src/locales/lang/zh.ts
  src/store/modules/log.ts
  src/store/modules/trace.ts
  src/views/components/ConditionTags.vue
  src/views/dashboard/related/log/Header.vue
  src/views/dashboard/related/trace/Filter.vue
  src/views/dashboard/related/trace/components/Table/TableItem.vue
Labels: enhancement

#86 feat: support multiple trees for the flame graph
  src/store/modules/ebpf.ts
  src/views/components/ConditionTags.vue
  src/views/dashboard/related/ebpf/components/EBPFStack.vue
Labels: enhancement

#87 fix: the page doesn't need to be re-rendered when the url changes
  src/App.vue
  src/layout/components/SideBar.vue
  src/views/dashboard/related/ebpf/components/EBPFStack.vue
Labels: bug

#88 fix: set duration time
  src/layout/components/AppMain.vue
  src/layout/components/NavBar.vue
  src/main.ts
  src/store/modules/dashboard.ts
  src/store/modules/ebpf.ts
  src/store/modules/event.ts
  src/store/modules/log.ts
  src/store/modules/profile.ts
  src/store/modules/selectors.ts
  src/store/modules/trace.ts
Labels: bug

#89 feat: remove unexpected data for exporting dashboards
  src/hooks/useProcessor.ts
  src/types/dashboard.d.ts
  src/views/dashboard/List.vue
Labels: enhancement

#90 fix: polish the eBPF profiling widget
  src/types/ebpf.d.ts
  src/views/dashboard/related/ebpf/Content.vue
  src/views/dashboard/related/ebpf/components/EBPFSchedules.vue
  src/views/dashboard/related/ebpf/components/EBPFStack.vue
  src/views/dashboard/related/ebpf/components/NewTask.vue
Labels: bug

#93 feat: remove the total filed from query conditions
  src/graphql/fragments/log.ts
  src/graphql/fragments/trace.ts
  src/store/modules/log.ts
  src/store/modules/trace.ts
  src/views/dashboard/related/components/LogTable/Index.vue
  src/views/dashboard/related/log/Header.vue
  src/views/dashboard/related/log/List.vue
  src/views/dashboard/related/trace/Detail.vue
  src/views/dashboard/related/trace/Filter.vue
  src/views/dashboard/related/trace/TraceList.vue
  src/views/dashboard/related/trace/components/D3Graph/SpanDetail.vue
Labels: enhancement

#94 feat: remove needTotal and total fields from query conditions
  src/graphql/fragments/alarm.ts
  src/graphql/fragments/event.ts
  src/graphql/fragments/log.ts
  src/store/modules/event.ts
  src/views/alarm/Header.vue
  src/views/dashboard/related/log/Header.vue
  src/views/event/Header.vue
Labels: enhancement

#95 fix: update query conditions for browser logs
  src/locales/lang/en.ts
  src/locales/lang/zh.ts
  src/views/dashboard/related/log/Header.vue
  src/views/dashboard/related/trace/Filter.vue
Labels: bug

#96 Add Spanish Translation
  src/locales/lang/es.ts
Labels: enhancement

#97 feat: visualize the OFF CPU eBPF profiling
  src/graphql/fragments/ebpf.ts
  src/store/modules/ebpf.ts
  src/views/dashboard/related/ebpf/Content.vue
  src/views/dashboard/related/ebpf/components/EBPFSchedules.vue
  src/views/dashboard/related/ebpf/components/NewTask.vue
  src/views/dashboard/related/ebpf/components/TaskList.vue
  src/views/dashboard/related/ebpf/components/data.ts
Labels: enhancement

#98 feat: add a Spanish option in the lang selector
  src/constants/data.ts
  src/layout/components/SideBar.vue
  src/locales/index.ts
  src/views/Settings.vue
  src/views/dashboard/related/ebpf/components/EBPFStack.vue
Labels: bug, enhancement

#100 feat: sort spans with `startTime` or `spanId` in a segment
  src/store/modules/ebpf.ts
  src/types/trace.d.ts
  src/views/dashboard/graphs/TopList.vue
  src/views/dashboard/graphs/components/ColumnGraph.vue
  src/views/dashboard/related/ebpf/Content.vue
  src/views/dashboard/related/ebpf/components/EBPFSchedules.vue
  src/views/dashboard/related/ebpf/components/EBPFStack.vue
  src/views/dashboard/related/profile/Content.vue
  src/views/dashboard/related/trace/Detail.vue
  src/views/dashboard/related/trace/components/D3Graph/Index.vue
  src/views/dashboard/related/trace/components/D3Graph/SpanDetail.vue
Labels: bug, enhancement

#101 feat: add `Percentage Of Root` and `Percentage Of Selected` in the eBPF widget
  src/types/ebpf.d.ts
  src/views/dashboard/related/ebpf/components/EBPFSchedules.vue
  src/views/dashboard/related/ebpf/components/EBPFStack.vue
Labels: enhancement
