Repository apache/skywalking-booster-ui, pull requests merged in 2023-04, with the labels that each got.

#251 fix: polish tooltips for trace profiling widget
  src/views/dashboard/related/trace/components/Table/TableItem.vue
  src/views/dashboard/related/trace/utils/d3-trace-list.ts
Labels: bug

#253 Add Redis Menu
  src/locales/lang/en.ts
  src/locales/lang/es.ts
  src/locales/lang/zh.ts
  src/router/data/database.ts
Labels: enhancement

#254 types: optimize data types
  src/assets/img/icons.ts
  src/components/DateCalendar.vue
  src/components/Graph.vue
  src/components/SelectSingle.vue
  src/components/Selector.vue
  src/components/TimePicker.vue
  src/components/index.ts
  src/hooks/data.ts
  src/hooks/useAssociateProcessor.ts
  src/hooks/useBreakpoint.ts
  src/hooks/useDashboardsSession.ts
  src/hooks/useEcharts.ts
  src/hooks/useEventListener.ts
  src/hooks/useLegendProcessor.ts
  src/hooks/useListConfig.ts
  src/hooks/useMetricsProcessor.ts
  src/hooks/useTimeout.ts
  src/layout/components/NavBar.vue
  src/layout/components/SideBar.vue
  src/store/modules/alarm.ts
  src/store/modules/app.ts
  src/store/modules/dashboard.ts
  src/store/modules/demand-log.ts
  src/store/modules/ebpf.ts
  src/store/modules/event.ts
  src/store/modules/log.ts
  src/store/modules/network-profiling.ts
  src/store/modules/profile.ts
  src/store/modules/selectors.ts
  src/store/modules/topology.ts
  src/store/modules/trace.ts
  src/types/global.d.ts
  src/views/dashboard/controls/Widget.vue
  src/views/dashboard/graphs/TopList.vue
  src/views/dashboard/related/topology/components/Graph.vue
  src/views/dashboard/related/trace/Detail.vue
  src/views/dashboard/related/trace/Filter.vue
  src/views/dashboard/related/trace/Header.vue
  src/views/dashboard/related/trace/Index.vue
  src/views/dashboard/related/trace/TraceList.vue
  src/views/dashboard/related/trace/components/D3Graph/Index.vue
  src/views/dashboard/related/trace/components/D3Graph/SpanDetail.vue
  src/views/dashboard/related/trace/components/List.vue
  src/views/dashboard/related/trace/components/Statistics.vue
  src/views/dashboard/related/trace/components/Table/Index.vue
  src/views/dashboard/related/trace/components/Table/TableContainer.vue
  src/views/dashboard/related/trace/components/Table/TableItem.vue
  src/views/dashboard/related/trace/utils/d3-trace-list.ts
  src/views/dashboard/related/trace/utils/d3-trace-tree.ts
  src/views/dashboard/related/trace/utils/trace-table.ts
Labels: enhancement

#258 feat: set default value for `showSymbol` in the line graph
  src/views/dashboard/configuration/widget/graph-styles/Line.vue
  src/views/dashboard/data.ts
  src/views/dashboard/graphs/Line.vue
Labels: enhancement

#259 feat: update options for line graph
  src/views/dashboard/graphs/Line.vue
Labels: enhancement

#260 build(deps): bump element-plus from 2.0.2 to 2.1.0
  package-lock.json
  package.json
  src/views/dashboard/graphs/Card.vue
  src/views/dashboard/graphs/EndpointList.vue
  src/views/dashboard/graphs/InstanceList.vue
  src/views/dashboard/graphs/ServiceList.vue
  src/views/dashboard/graphs/style.scss
  src/views/dashboard/panel/Tool.vue
Labels: dependencies
