Repository apache/skywalking-booster-ui, pull requests merged in 2023-11, with the labels that each got.

#333 refactor: update Logs view
  src/locales/lang/en.ts
  src/locales/lang/es.ts
  src/locales/lang/zh.ts
  src/views/dashboard/related/log/LogTable/Index.vue
  src/views/dashboard/related/log/LogTable/LogDetail.vue
  src/views/dashboard/related/log/LogTable/LogService.vue
  src/views/dashboard/related/log/LogTable/data.ts
Labels: enhancement

#336 feat: enhance the Dark Theme
  src/components/Graph.vue
  src/hooks/data.ts
  src/hooks/useLegendProcessor.ts
  src/styles/reset.scss
  src/styles/theme.scss
  src/views/dashboard/controls/Tab.vue
  src/views/dashboard/graphs/Bar.vue
  src/views/dashboard/graphs/Line.vue
  src/views/dashboard/graphs/components/Legend.vue
  src/views/dashboard/panel/Layout.vue
  src/views/dashboard/related/topology/components/Sankey.vue
Labels: enhancement

#337 fix: set the height for trace widget
  src/views/dashboard/related/trace/Index.vue
Labels: bug

#339 refactor: enhance the Log widget
  src/styles/theme.scss
  src/views/dashboard/related/log/LogTable/Index.vue
  src/views/dashboard/related/log/LogTable/LogDetail.vue
  src/views/dashboard/related/log/LogTable/LogService.vue
  src/views/dashboard/related/log/LogTable/data.ts
  src/views/dashboard/related/trace/components/Table/TableItem.vue
Labels: enhancement

#340 fix: change log widget and loading mask style
  src/styles/theme.scss
  src/views/dashboard/related/log/LogTable/LogDetail.vue
  src/views/dashboard/related/log/LogTable/LogService.vue
Labels: bug

#341 fix: polish list style
  src/views/dashboard/graphs/style.scss
Labels: bug

#342 feat: support to save and load theme setting from localStorage
  src/layout/components/NavBar.vue
Labels: enhancement

#343 fix: the service parameter is wrong when the view dump from Log to Trace widget by clicking traceID
  src/views/dashboard/related/log/LogTable/LogService.vue
  src/views/dashboard/related/trace/Filter.vue
Labels: bug

#344 feat: enhance topology layout and fix calls metrics
  src/store/modules/dashboard.ts
  src/styles/theme.scss
  src/views/dashboard/data.ts
  src/views/dashboard/related/topology/components/Graph.vue
  src/views/dashboard/related/topology/components/PodTopology.vue
  src/views/dashboard/related/topology/components/Settings.vue
Labels: bug, enhancement

#345 fix: change metrics config, fix tab routes
  src/hooks/useExpressionsProcessor.ts
  src/router/layer.ts
  src/views/dashboard/related/topology/components/Graph.vue
  src/views/dashboard/related/topology/components/Metrics.vue
  src/views/dashboard/related/topology/components/Settings.vue
Labels: bug

#346 fix: change colors to match dark theme for Network Profiling
  src/assets/icons/add_fill.svg
  src/views/dashboard/controls/Tab.vue
  src/views/dashboard/related/continuous-profiling/components/PolicyList.vue
  src/views/dashboard/related/network-profiling/components/ProcessTopology.vue
  src/views/dashboard/related/network-profiling/components/Settings.vue
  src/views/dashboard/related/network-profiling/components/Tasks.vue
Labels: bug

#349 refactor: reduce component chunks to improve page loading resource time
  src/router/alarm.ts
  src/router/dashboard.ts
  src/router/layer.ts
  src/router/marketplace.ts
  src/router/settings.ts
Labels: bug
