Repository apache/skywalking-booster-ui, pull requests merged in 2023-07, with the labels that each got.

#294 init minTime to Infinity
  src/views/dashboard/related/trace/components/Statistics.vue
Labels: bug

#295 fix: minTraceDuration and maxTraceDuration types
  src/views/dashboard/related/trace/Header.vue
Labels: bug

#297 feat: Implement customize menus
  src/assets/icons/aws_cloud.svg
  src/assets/icons/browser.svg
  src/assets/icons/database.svg
  src/assets/icons/general_service.svg
  src/assets/icons/infrastructure.svg
  src/assets/icons/kubernetes.svg
  src/assets/icons/marketplace.svg
  src/assets/icons/self_observability.svg
  src/assets/icons/service_mesh.svg
  src/graphql/fragments/app.ts
  src/graphql/query/app.ts
  src/layout/components/NavBar.vue
  src/layout/components/SideBar.vue
  src/locales/lang/en.ts
  src/locales/lang/es.ts
  src/locales/lang/zh.ts
  src/router/alarm.ts
  src/router/dashboard.ts
  src/router/data/aws.ts
  src/router/data/browser.ts
  src/router/data/database.ts
  src/router/data/functions.ts
  src/router/data/gateway.ts
  src/router/data/general.ts
  src/router/data/index.ts
  src/router/data/infrastructure.ts
  src/router/data/k8s.ts
  src/router/data/selfObservability.ts
  src/router/data/serviceMesh.ts
  src/router/index.ts
  src/router/layer.ts
  src/router/marketplace.ts
  src/router/setting.ts
  src/store/modules/app.ts
  src/types/app.d.ts
  src/types/components.d.ts
  src/utils/cancelToken.ts
  src/views/marketplace/Menus.vue
  src/views/marketplace/Settings.vue
  vite.config.ts
Labels: enhancement

#299 feat: menus support for multiple languages
  src/graphql/fragments/app.ts
  src/layout/components/SideBar.vue
  src/locales/lang/en.ts
  src/locales/lang/es.ts
  src/locales/lang/menus/en.ts
  src/locales/lang/menus/es.ts
  src/locales/lang/menus/zh.ts
  src/locales/lang/zh.ts
  src/router/alarm.ts
  src/router/dashboard.ts
  src/router/layer.ts
  src/router/marketplace.ts
  src/router/settings.ts
  src/store/modules/app.ts
  src/types/app.d.ts
  src/views/Marketplace.vue
  src/views/Settings.vue
  src/views/alarm/Header.vue
  src/views/dashboard/related/event/Header.vue
  src/views/dashboard/related/log/List.vue
  src/views/dashboard/related/trace/TraceList.vue
  src/views/dashboard/related/trace/components/D3Graph/SpanDetail.vue
  vite.config.ts
Labels: enhancement

#300 fix: set chart label
  src/hooks/useExpressionsProcessor.ts
Labels: bug

#302 feat: add MongoDB menu i18n(#11045)
  src/locales/lang/menus/en.ts
  src/locales/lang/menus/es.ts
  src/locales/lang/menus/zh.ts
Labels: enhancement

#303 feat: use `title` instead of `i18nKey` for menus.
  src/layout/components/SideBar.vue
  src/router/alarm.ts
  src/router/dashboard.ts
  src/router/marketplace.ts
  src/router/settings.ts
Labels: enhancement

#304 Fix Virtual_MQ spelling mistake
  src/locales/lang/menus/en.ts
Labels: bug

#305 fix: polish names and descriptions on the marketplace page
  src/views/Marketplace.vue
Labels: enhancement

#306 fix: commit error on Windows
  .husky/commit-msg
  .husky/pre-commit
Labels: bug

#307 fix: remove node-sass
  package-lock.json
  package.json
Labels: dependencies
