Repository apache/skywalking-booster-ui, pull requests merged in 2024-01, with the labels that each got.

#356 perf(Theme): add theme change animation
  src/layout/components/NavBar.vue
  src/styles/theme.scss
  src/types/global.d.ts
Labels: enhancement

#358 feat: add `expressions` to dashboard configurations on the dashboard list page
  src/components/Tags.vue
  src/locales/lang/en.ts
  src/locales/lang/es.ts
  src/locales/lang/zh.ts
  src/types/dashboard.d.ts
  src/views/dashboard/List.vue
Labels: enhancement

#360 feat: implement the Service and Instance hierarchy topology.
  src/assets/icons/hierarchy_topology.svg
  src/assets/img/tools/BROWSER.png
  src/assets/img/tools/DATABASE.png
  src/assets/img/tools/ELASTICSEARCH.png
  src/assets/img/tools/GENERAL.png
  src/assets/img/tools/K8S.png
  src/assets/img/tools/K8S_SERVICE.png
  src/assets/img/tools/MESH.png
  src/assets/img/tools/MESH_CP.png
  src/assets/img/tools/MESH_DP.png
  src/assets/img/tools/MONGODB.png
  src/assets/img/tools/MQ.png
  src/assets/img/tools/NGINX.png
  src/assets/img/tools/OS_LINUX.png
  src/assets/img/tools/POSTGRESQL.png
  src/assets/img/tools/RABBITMQ.png
  src/assets/img/tools/VIRTUAL_CACHE.png
  src/assets/img/tools/VIRTUAL_DATABASE.png
  src/assets/img/tools/VIRTUAL_GATEWAY.png
  src/components/SelectSingle.vue
  src/components/Tags.vue
  src/graphql/fragments/topology.ts
  src/graphql/query/topology.ts
  src/hooks/useDashboardsSession.ts
  src/hooks/useExpressionsProcessor.ts
  src/locales/lang/en.ts
  src/locales/lang/es.ts
  src/locales/lang/zh.ts
  src/store/modules/topology.ts
  src/styles/theme.scss
  src/types/dashboard.d.ts
  src/types/topology.d.ts
  src/views/dashboard/List.vue
  src/views/dashboard/data.ts
  src/views/dashboard/panel/Tool.vue
  src/views/dashboard/related/topology/Index.vue
  src/views/dashboard/related/topology/components/Graph.vue
  src/views/dashboard/related/topology/components/utils/layout.ts
  src/views/dashboard/related/topology/config/Metrics.vue
  src/views/dashboard/related/topology/config/Settings.vue
  src/views/dashboard/related/topology/pod/InstanceMap.vue
  src/views/dashboard/related/topology/pod/PodMap.vue
  src/views/dashboard/related/topology/pod/Sankey.vue
  src/views/dashboard/related/topology/service/HierarchyMap.vue
  src/views/dashboard/related/topology/service/ServiceMap.vue
Labels: enhancement

#361 fix: link addresses on hierarchy topology nodes
  src/types/topology.d.ts
  src/views/dashboard/related/topology/pod/InstanceMap.vue
  src/views/dashboard/related/topology/service/HierarchyMap.vue
Labels: bug

#362 fix: polish the hierarchy topology and dashboard configs
  src/locales/lang/en.ts
  src/locales/lang/es.ts
  src/locales/lang/zh.ts
  src/views/dashboard/List.vue
  src/views/dashboard/related/topology/pod/InstanceMap.vue
  src/views/dashboard/related/topology/service/HierarchyMap.vue
Labels: bug, enhancement

#363 fix: import dashboard templates
  src/store/modules/dashboard.ts
  src/views/dashboard/List.vue
  src/views/dashboard/related/topology/config/Metrics.vue
Labels: bug

#364 fix: process dashboard templates for the new config
  src/store/modules/dashboard.ts
Labels: bug

#365 fix: optimize tooltips style
  src/views/dashboard/panel/Tool.vue
  src/views/dashboard/related/topology/components/Graph.vue
  src/views/dashboard/related/topology/pod/InstanceMap.vue
  src/views/dashboard/related/topology/service/HierarchyMap.vue
  src/views/dashboard/related/topology/service/ServiceMap.vue
  src/views/dashboard/related/topology/style.scss
Labels: bug

#367 fix: resizing window causes the trace graph to display incorrectly
  src/utils/debounce.ts
  src/views/dashboard/controls/Trace.vue
  src/views/dashboard/related/trace/Detail.vue
  src/views/dashboard/related/trace/TraceList.vue
  src/views/dashboard/related/trace/components/D3Graph/Index.vue
  src/views/dashboard/related/trace/utils/d3-trace-list.ts
  src/views/dashboard/related/trace/utils/d3-trace-tree.ts
Labels: bug

#369 fix: enhance VNode logic and support multiple Trace IDs in span's ref
  src/hooks/useDashboardsSession.ts
  src/store/modules/dashboard.ts
  src/views/dashboard/related/trace/Filter.vue
  src/views/dashboard/related/trace/TraceList.vue
  src/views/dashboard/related/trace/components/D3Graph/Index.vue
  src/views/dashboard/related/trace/components/D3Graph/SpanDetail.vue
Labels: bug

#370 feat: add the `layers` filed and associate layers dashboards for the service topology nodes
  src/graphql/fragments/topology.ts
  src/store/modules/topology.ts
  src/types/topology.d.ts
  src/views/dashboard/related/topology/service/ServiceMap.vue
Labels: enhancement
