Repository apache/skywalking-booster-ui, pull requests merged in 2024-10, with the labels that each got.

#419 feat: add content decorations to Table and Card widgets
  src/locales/lang/en.ts
  src/locales/lang/es.ts
  src/locales/lang/zh.ts
  src/types/dashboard.d.ts
  src/views/dashboard/Widget.vue
  src/views/dashboard/configuration/Widget.vue
  src/views/dashboard/configuration/widget/graph-styles/Card.vue
  src/views/dashboard/configuration/widget/graph-styles/Table.vue
  src/views/dashboard/configuration/widget/graph-styles/components/ContentDecorations.vue
  src/views/dashboard/graphs/Card.vue
  src/views/dashboard/graphs/Table.vue
Labels: enhancement

#420 feat: add `duration` to `findEndpoint`
  src/graphql/fragments/selector.ts
Labels: enhancement

#421 feat: support ranges for Value Mappings
  src/locales/lang/en.ts
  src/locales/lang/es.ts
  src/locales/lang/zh.ts
  src/types/dashboard.d.ts
  src/views/dashboard/Widget.vue
  src/views/dashboard/configuration/widget/graph-styles/Card.vue
  src/views/dashboard/configuration/widget/graph-styles/Table.vue
  src/views/dashboard/configuration/widget/graph-styles/components/ValueMappings.vue
  src/views/dashboard/graphs/Card.vue
  src/views/dashboard/graphs/Table.vue
Labels: enhancement

#422 Update mappingTip
  src/locales/lang/en.ts
  src/locales/lang/es.ts
  src/locales/lang/zh.ts
Labels: documentation

#423 Fix Value Mappings
  src/views/dashboard/configuration/widget/graph-styles/components/ValueMappings.vue
  src/views/dashboard/graphs/Card.vue
  src/views/dashboard/graphs/Table.vue
Labels: bug

#424 Fix initialization dashboards
  src/views/dashboard/panel/Layout.vue
Labels: bug
