Repository apache/skywalking-booster-ui, pull requests merged in 2025-03, with the labels that each got.

#452 Add skywalking go agent self observability menu
  src/locales/lang/menus/en.ts
  src/locales/lang/menus/es.ts
  src/locales/lang/menus/zh.ts
Labels: documentation

#453 fix: time range when generate link
  src/views/dashboard/components/WidgetLink.vue
Labels: bug

#454 build: remove `lodash` library
  package-lock.json
  package.json
  src/views/dashboard/related/trace/components/D3Graph/Index.vue
  src/views/dashboard/related/trace/utils/trace-table.ts
  vite.config.ts
Labels: dependencies

#459 feat: enhance trace list graph
  src/types/trace.d.ts
  src/views/dashboard/related/log/LogTable/Index.vue
  src/views/dashboard/related/trace/components/D3Graph/Index.vue
  src/views/dashboard/related/trace/components/D3Graph/SpanDetail.vue
  src/views/dashboard/related/trace/components/List.vue
  src/views/dashboard/related/trace/components/Table/Index.vue
  src/views/dashboard/related/trace/utils/d3-trace-list.ts
  src/views/dashboard/related/trace/utils/d3-trace-tree.ts
Labels: enhancement
